name: react-typescript-base

services:
    react-typescript-base-webapp:
        container_name: react-typescript-base-webapp
        build:
            dockerfile: docker/Dockerfile
        ports:
            - 80:8080
        volumes:
            - ./:/app
        command: "npm run start:dev"
