name: react-typescript-base

services:
    react-typescript-base-webapp:
        container_name: react-typescript-base-webapp
        build:
            dockerfile: docker/Dockerfile
        ports:
            - 80:8080
        volumes:
            - ./:/app
        entrypoint: ["/bin/sh", "-c", "npm install && npm run start:dev"]
